#!/bin/sh
#
# Copyright (C) 2014 Intel Corporation
#
# Load the CHIPSEC kernel module and invoke the chipsec main file.

# The below is replaced with the python site packages path during
# do_patch().
python PYTHONPATH/chipsec_main.py -v
