#!/bin/sh
#
# Copyright (C) 2014 Intel Corporation
#
# Load the CHIPSEC kernel module and invoke the chipsec main file.

modprobe -q chipsec
if [ $? -ne 0 ]; then
    exit 1
fi

# The below is replaced with the python site packages path during
# do_patch().
python PYTHONPATH/chipsec/chipsec_main.py -i -v
