#!/bin/sh
#
# Copyright 2017 Intel Corporation; author Megha Dey
#
# Script to run pstore tests
echo "Kernel pstore tests"

cd /usr/share/pstore-test/
if grep -q luv.pstore-tests /proc/cmdline; then
       ./pstore_tests
       ./pstore_crash_test
else
       if [ ! -e REBOOT_DIR/reboot_flag ]; then
              ./pstore_tests
       else
              ./pstore_post_reboot_tests
       fi
       rm -f REBOOT_DIR/prev_uuid
fi
