all:
	$(CC) -o umip_test umip_test.c
	$(CC) -o umip_test2_64 umip_test2.c
	$(CC) -o umip_test2_32 umip_test2.c
	$(CC) -o umip_pf normal_pf.c

.PHONY: clean
clean:
	rm -f umip_test
	rm -f umip_test2_64
	rm -f umip_test2_32
	rm -f umip_pf
