#!/bin/bash
#
# Copyright 2017 Intel Corporation; author Sai Praneeth Prakhya
#
# FWTS supports a debug option which dumps dmesg, cpuinfo and machine's
# ACPI tables. ACPI tables will be helpful for firmware engineers to
# debug errors in ACPI tables, similarly dmesg and cpuinfo can be used
# for post-mortem analysis. This script will create a directory named
# "dumps" in LUV RESULTS partiton and then will dump dmesg, cpuinfo
# and ACPI tables into that directory.
#
#####################################################################

# Definition for luv results folder
LUV_SAVE_RESULTS_DIR=$1

# Create a directory named "dumps" in luv results folder and run
# "fwts -d" command to dump dmesg, cpuinfo and ACPI tables
gen_dmesg_acpi_dumps() {
    mkdir -p ${LUV_SAVE_RESULTS_DIR}/dumps
    if [ $? -eq 0 ] ; then
        cd ${LUV_SAVE_RESULTS_DIR}/dumps
        fwts -d
    else
        echo "Failed to create dumps directory"
    fi
}

gen_dmesg_acpi_dumps
