#!/bin/bash
#
# Copyright 2018 Intel Corporation; author Megha Dey
#
LUVDEBUG_LOG=/tmp/luv-debug.log

setup_debug_log()
{
    grep -q luv\.debug /proc/cmdline
    if [ $? -eq 0 ]; then
        echo "Enable LUV debug mode..."
        LUVDEBUG="1"
        set -x
        set -v
    fi
}

setup_output()
{
    thistty=$(tty)

    if [ ! -z ${LUVDEBUG} ]; then
        logfiles="${thistty} ${LUVDEBUG_LOG}"
    else
        logfiles="${thistty}"
    fi

    exec &> >(tee -a ${logfiles})
}

print_line()
{
    while read line ; do
    case $line in
        *+* )
        echo "[    `cut -d " " -f 1 /proc/uptime`0000]  $line"
        ;;
        * )
        echo "[    `cut -d " " -f 1 /proc/uptime`0000] $line"
        ;;
    esac
    done
}

luv_msg_write() {
    /bin/plymouth display-message --text="$1"

    if [ $# == 2 ]; then
         sleep $2
         luv_msg_hide $1
    fi

    echo "$1" | print_line
}

luv_msg_hide() {
    /bin/plymouth hide-message --text="$1"
}

setup_debug_log
setup_output
