#!/bin/bash
#
# Copyright 2018 Intel Corporation; author Megha Dey
#

luv_msg_write() {
    /bin/plymouth display-message --text="$1"

    if [ $# == 2 ]; then
         sleep $2
         plymouth_hide "$1"
    fi

    echo "$1" >&2

    if [ ! -z ${LUVDEBUG} ]; then
        echo LUV_MESSAGE-$1>> ${LUV_SAVE_RESULTS_DIR}luv-debug.log
    fi
}

luv_msg_hide() {
    /bin/plymouth hide-message --text="$1"
}
