#!/bin/sh
#
# Parse the output of ndctl and write a luv-test-manager compatible
# log to stdout.

awk -F: '

function test_info(test_name, results) {
        "date +%H:%M:%S:%N" | getline current_time;
        close ("date +%H:%M:%S:%N");
        gsub(/TEST_NAME/, test_name, info);
        info = info "1.1 " current_time " ndctl "test_name " RESULT " results "\r\n";
        info = info "1.1 " current_time  " ndctl " test_name  " END";
        return info;
}

!/LUV/  {
        if (info == "") {
            "date +%H:%M:%S:%N" | getline current_time;
            close ("date +%H:%M:%S:%N");
            info = "1.1 " current_time " ndctl TEST_NAME START\n";
        }
        info = info "1.1 " current_time " ndctl TEST_NAME INFO " $0 "\n";
        }

/\ERROR/ {
        results = "0 0 0 0 1";
        print test_info($1, results);
        info = ""

	fflush("");
	}

/\SKIP/ {
        results =  "0 0 0 1 0";
        print test_info($1, results);
        info = ""

        fflush("");
        }

/\FAIL/ {
        results = "0 1 0 0 0";
        print test_info($1, results);
        info = ""

        fflush("");
        }

/\PASS/ {
        results = "1 0 0 0 0";
        print test_info($1, results);
        info = ""

        fflush("");
        }'
