#!/bin/sh
#
# Parse the output of fwts and write a luv-test-manager compatible log
# to stdout.

# - cut out blank lines
# - strip the summary at the end, it's duplicate info
# - only include info about test passes/fails, etc
# - print in luv-test-manager format

awk '!/^summary/ && !/^fwts/ && /\;SUM.*passed|\;INF/ {
	"date +%H:%M:%S:%N" | getline current_time;
	close ("date +%H:%M:%S:%N")
	if ($2 == ";SUM") {
		printf ("1.1 %s fwts %s RESULT %d %d %d %d\n",
			current_time, $1, $3, $5, $7, $9);
		fflush("");
	} else if ($2 == ";INF") {
		printf ("1.1 %s fwts %s INFO %s\n", current_time, $1, substr($0, index($0, $8)));
		fflush("");
	}
}'
